
package Formularios;

import DbContext.DiagnosticosCtx;
import DbContext.EmpleadosCtx;
import Mapeo.TiempoPromedio;
import Entidades.Diagnosticos;
import Entidades.Empleados;
import Fuentes.Tipografia;
import java.util.List;
import com.formdev.flatlaf.FlatLightLaf;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;


public class AdministradorFrm extends javax.swing.JFrame {

    DiagnosticosCtx diagnosticosCtx = new DiagnosticosCtx();
    EmpleadosCtx empleadosCtx = new EmpleadosCtx();
    
    DefaultTableModel modeloClase = new DefaultTableModel();
    DefaultTableModel modeloMes = new DefaultTableModel();
    DefaultTableModel modeloTotal = new DefaultTableModel();
    DefaultTableModel modeloTiempo = new DefaultTableModel();
    DefaultTableModel modeloEmpleados = new DefaultTableModel();
    
    String[] clase = {"Matrícula", "Fecha", "Resultado", "Observaciones"};
    String[] mes = {"Matrícula", "Fecha", "Resultado", "Observaciones"};
    String[] total = {"Mecánico", "Credencial", "Nombre", "Teléfono", "Matrícula", "Tipo", "Fecha", "Resultado", "Observaciones"};
    String[] tiempo = {"Clase", "Tiempo Promedio de Diagnóstico en Minutos"};
    String[] empleados = {"Credencial", "Nombre", "Estado", "Rol"};
    
    public AdministradorFrm() {
        initComponents();
        
        Tipografia font = new Tipografia("Fuente.ttf", 10f);
        font.asignarFuente(this);
        
        modeloClase.setColumnIdentifiers(clase);
        modeloMes.setColumnIdentifiers(mes);
        modeloTotal.setColumnIdentifiers(total);
        modeloTiempo.setColumnIdentifiers(tiempo);
        modeloEmpleados.setColumnIdentifiers(empleados);
        
        tb_clase.setModel(modeloClase);
        tb_mes.setModel(modeloMes);
        tb_total.setModel(modeloTotal);
        tb_tiempo_promedio.setModel(modeloTiempo);
        tb_empleados.setModel(modeloEmpleados);
        
        inicializarPromediosDeTiempo();
        obtenerTodosLosEmpleados();
        
    }
    
    public void inicializarPromediosDeTiempo() {
        try {
            List<TiempoPromedio> promedios = diagnosticosCtx.todosPromediosDeTiempo();

            modeloTiempo.setRowCount(0);
            for (int i = 0; i < promedios.size(); i++) {
                modeloTiempo.addRow(new Object[] {
                    promedios.get(i).getTipo(),
                    Math.round(promedios.get(i).getMinutos()),
                });
            }

        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }
    
    public void obtenerTodosLosEmpleados() {
        try {
            List<Empleados> empleados = empleadosCtx.obtenerTodosLosEmpleados();

            modeloEmpleados.setRowCount(0);
            for (int i = 0; i < empleados.size(); i++) {
                modeloEmpleados.addRow(new Object[] {
                    empleados.get(i).getDocumento(),
                    empleados.get(i).getNombre(),
                    empleados.get(i).getEstaActivo() ? "Desbloqueado" : "Bloqueado",
                    empleados.get(i).getFkRolId().getRol()
                });
            }

        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }
    
    private void mostrarMensajeError(Exception e) {
        JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void bloquearDesbloquearEmpleado() throws Exception {
        int filaSeleccionada = tb_empleados.getSelectedRow();

        if (filaSeleccionada == -1) throw new Exception("Seleccione una fila. Por Favor.");

        String credencial = (String) tb_empleados.getValueAt(filaSeleccionada, 0);

        empleadosCtx.actualizarEstadoEmpleado(credencial);

        JOptionPane.showMessageDialog(rootPane, "Empleado actualizado correctamente.");

        obtenerTodosLosEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_clase = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbx_clase = new javax.swing.JComboBox<>();
        btn_buscar_por_clase = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        j_year = new com.toedter.calendar.JYearChooser();
        j_month = new com.toedter.calendar.JMonthChooser();
        btn_buscar_por_mes = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_mes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        j_year_total = new com.toedter.calendar.JYearChooser();
        btn_buscar_total = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_total = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_tiempo_promedio = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar_empleado = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_empleados = new javax.swing.JTable();
        btn_bloquear_empleado = new javax.swing.JButton();
        btn_desbloquear_empleado = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_matricula = new javax.swing.JMenu();
        mn_cliente = new javax.swing.JMenu();
        mn_roles = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N

        tb_clase.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        tb_clase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_clase.setPreferredSize(new java.awt.Dimension(300, 85));
        jScrollPane3.setViewportView(tb_clase);

        jLabel5.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel5.setText("Clase:");

        cbx_clase.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        cbx_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motoclicletas", "Automoviles", "Camionetas", "Furgonetas", "Camiones", "Buses", "Taxis", "Remolques", "Servicio Especial", "Hibridos" }));
        cbx_clase.setPreferredSize(new java.awt.Dimension(72, 25));

        btn_buscar_por_clase.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_buscar_por_clase.setText("Encontrar");
        btn_buscar_por_clase.setPreferredSize(new java.awt.Dimension(75, 25));
        btn_buscar_por_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_por_claseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel6.setText("Comandos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_por_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_clase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_buscar_por_clase, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Diagnostico Tipo", jPanel3);

        jLabel7.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel7.setText("Calendario:");

        j_year.setPreferredSize(new java.awt.Dimension(64, 25));

        j_month.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N

        btn_buscar_por_mes.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_buscar_por_mes.setText("Encontrar");
        btn_buscar_por_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_por_mesActionPerformed(evt);
            }
        });

        tb_mes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tb_mes);

        jLabel4.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel4.setText("Comandos:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j_year, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(j_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_por_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j_month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_buscar_por_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Diagnostico Mes", jPanel4);

        jLabel1.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel1.setText("Calendario:");

        btn_buscar_total.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_buscar_total.setText("Encontrar");
        btn_buscar_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_totalActionPerformed(evt);
            }
        });

        tb_total.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_total);

        jLabel3.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel3.setText("Comandos:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j_year_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_total, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_buscar_total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(j_year_total, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Diagnosticos", jPanel5);

        tb_tiempo_promedio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_tiempo_promedio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tiempo Promedio ", jPanel1);

        jLabel2.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        jLabel2.setText("Comandos:");

        btn_eliminar_empleado.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_eliminar_empleado.setText("Eliminar");
        btn_eliminar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_empleadoActionPerformed(evt);
            }
        });

        tb_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb_empleados);

        btn_bloquear_empleado.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_bloquear_empleado.setText("Bloquear");
        btn_bloquear_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bloquear_empleadoActionPerformed(evt);
            }
        });

        btn_desbloquear_empleado.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_desbloquear_empleado.setText("Desbloquear");
        btn_desbloquear_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desbloquear_empleadoActionPerformed(evt);
            }
        });

        btn_Actualizar.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bloquear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_desbloquear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bloquear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_desbloquear_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", jPanel2);

        jMenuBar1.setFont(new java.awt.Font("Geist Mono Light", 0, 12)); // NOI18N

        mn_matricula.setText("Vehiculo");
        mn_matricula.setPreferredSize(new java.awt.Dimension(83, 22));
        mn_matricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_matriculaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mn_matricula);

        mn_cliente.setText("Cliente");
        mn_cliente.setPreferredSize(new java.awt.Dimension(85, 32));
        mn_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_clienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(mn_cliente);

        mn_roles.setText("Empleados");
        mn_roles.setPreferredSize(new java.awt.Dimension(85, 22));
        mn_roles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mn_rolesMousePressed(evt);
            }
        });
        jMenuBar1.add(mn_roles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_matriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_matriculaMouseClicked
        try {
            VehiculoFrm frmMatricula = new VehiculoFrm();
            frmMatricula.setVisible(true);
        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_mn_matriculaMouseClicked

    private void mn_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_clienteMouseClicked
        try {
            ClienteFrm frmCliente = new ClienteFrm();
            frmCliente.setVisible(true);
        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_mn_clienteMouseClicked

    private void mn_rolesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_rolesMousePressed
        try {
            RolesFrm frmRoles = new RolesFrm();
            frmRoles.setVisible(true);
        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_mn_rolesMousePressed

    private void btn_buscar_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_totalActionPerformed

        try{
            int año = j_year_total.getYear();

            List<Diagnosticos> diagnosticos = diagnosticosCtx.todosDiagnosticosPorAñoConClientes(año);

            modeloTotal.setRowCount(0);
            for (int i = 0; i < diagnosticos.size(); i++) {
                modeloTotal.addRow(new Object[] {
                    diagnosticos.get(i).getFkEmpleadoId().getNombre(),
                    diagnosticos.get(i).getFkVehiculoId().getFkClienteId().getCredencial(),
                    diagnosticos.get(i).getFkVehiculoId().getFkClienteId().getNombre(),
                    diagnosticos.get(i).getFkVehiculoId().getFkClienteId().getTelefono(),
                    diagnosticos.get(i).getFkVehiculoId().getMatricula(),
                    diagnosticos.get(i).getFkVehiculoId().getTipo(),
                    new SimpleDateFormat("yyyy-MM-dd").format(diagnosticos.get(i).getFecha()),
                    diagnosticos.get(i).getResultado(),
                    diagnosticos.get(i).getObservaciones()
                });
            }
        }catch(Exception e){
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_buscar_totalActionPerformed

    private void btn_buscar_por_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_por_mesActionPerformed
        // TODO add your handling code here:
        try{
            int año = j_year.getYear();
            int mes = j_month.getMonth();

            List<Diagnosticos> diagnosticos = diagnosticosCtx.todosDiagnosticosPorMes(año, mes + 1);

            modeloMes.setRowCount(0);
            for (int i = 0; i < diagnosticos.size(); i++) {
                modeloMes.addRow(new Object[] {
                    diagnosticos.get(i).getFkVehiculoId().getMatricula(),
                    new SimpleDateFormat("yyyy-MM-dd").format(diagnosticos.get(i).getFecha()),
                    diagnosticos.get(i).getResultado(),
                    diagnosticos.get(i).getObservaciones()
                });
            }

        }catch(Exception e){
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_buscar_por_mesActionPerformed

    private void btn_buscar_por_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_por_claseActionPerformed
        // TODO add your handling code here:
        try{
            String tipo = (String) cbx_clase.getSelectedItem();

            List<Diagnosticos> diagnosticos = diagnosticosCtx.todosDiagnosticosPorTipo(tipo);
            
            modeloClase.setRowCount(0);
            for (int i = 0; i < diagnosticos.size(); i++) {
                modeloClase.addRow(new Object[] {
                    diagnosticos.get(i).getFkVehiculoId().getMatricula(),
                    new SimpleDateFormat("yyyy-MM-dd").format(diagnosticos.get(i).getFecha()),
                    diagnosticos.get(i).getResultado(),
                    diagnosticos.get(i).getObservaciones()
                });
            }

        }catch(Exception e){
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_buscar_por_claseActionPerformed

    private void btn_eliminar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_empleadoActionPerformed
        try{
            int filaSeleccionada = tb_empleados.getSelectedRow();
        
            if (filaSeleccionada == -1) throw new Exception("Seleccione una fila. Por Favor.");

            String rol = (String) tb_empleados.getValueAt(filaSeleccionada, 3);

            if (!rol.equals("ADMINISTRADOR")) throw new Exception("Solo se pueden eliminar cuentas de administrador.");

            String credencial = (String) tb_empleados.getValueAt(filaSeleccionada, 0);

            empleadosCtx.eliminarEmpleadoPorCredencial(credencial);

            modeloEmpleados.removeRow(filaSeleccionada);

            JOptionPane.showMessageDialog(rootPane, "Empleado eliminado correctamente.");

            obtenerTodosLosEmpleados();
        }catch(Exception e){
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_eliminar_empleadoActionPerformed

    private void btn_bloquear_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bloquear_empleadoActionPerformed
        try {
            bloquearDesbloquearEmpleado();
        } catch (Exception e) {
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_bloquear_empleadoActionPerformed

    private void btn_desbloquear_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desbloquear_empleadoActionPerformed
        try {
            bloquearDesbloquearEmpleado();
        } catch (Exception e) {
           mostrarMensajeError(e);
        }
    }//GEN-LAST:event_btn_desbloquear_empleadoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try{
            SessionFrm frmLogin = new SessionFrm();
            frmLogin.setVisible(true);
            frmLogin.setLocationRelativeTo(null);
            this.dispose();
        }catch(Exception e){
            mostrarMensajeError(e);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        obtenerTodosLosEmpleados();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); 
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministradorFrm form = new AdministradorFrm();
                form.setVisible(true);
                form.setResizable(false);
                form.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_bloquear_empleado;
    private javax.swing.JButton btn_buscar_por_clase;
    private javax.swing.JButton btn_buscar_por_mes;
    private javax.swing.JButton btn_buscar_total;
    private javax.swing.JButton btn_desbloquear_empleado;
    private javax.swing.JButton btn_eliminar_empleado;
    private javax.swing.JComboBox<String> cbx_clase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JMonthChooser j_month;
    private com.toedter.calendar.JYearChooser j_year;
    private com.toedter.calendar.JYearChooser j_year_total;
    private javax.swing.JMenu mn_cliente;
    private javax.swing.JMenu mn_matricula;
    private javax.swing.JMenu mn_roles;
    private javax.swing.JTable tb_clase;
    private javax.swing.JTable tb_empleados;
    private javax.swing.JTable tb_mes;
    private javax.swing.JTable tb_tiempo_promedio;
    private javax.swing.JTable tb_total;
    // End of variables declaration//GEN-END:variables
}
